### ISSUE TITLE
Investigate long loading times

### ISSUE THREAD

**Issue by zoey-kaiser** [sidebase/nuxt-auth-example#3] opened 2022-11-03 09:42 UTC
### Describe the bug

After deploying https://nuxt-auth-example.sidebase.io we noticed that the initial loading time is very high. This issue is to track down the reason and fix it, or add a loading indicator for when the page has not loaded yet.

**Comment by BracketJohn** [comment] 2022-11-17 16:13
I think the main reason for this is because we're using so small servers. I asked @DeusAvalon to have a look into this and scale up the instance. If the problem persists afterwards, we can investigate more, but I don't think it will.

**Comment by DeusAvalon** [comment] 2022-11-17 16:25
Im currently in the progress of snapshotting the instance but checking the CPU metrics doesnt show any shortage of resources at all:
<img width="822" alt="image" src="https://user-images.githubusercontent.com/42768942/202501220-08f2922d-d6ff-460e-be46-02be1c47feda.png">
We havent even touched our burst capacity once in the last 2 weeks. So i wouldnt be too sure that the root cause is the instance tho. @BracketJohn

**Comment by DeusAvalon** [comment] 2022-11-17 16:46
The instance has been moved to a twice as strong instance: `4 GB RAM, 2 vCPUs, 80 GB SSD`

Based on the metrics available right now when opening `https://nuxt-auth-example.sidebase.io` the instance should be ridicolously overspec'd and the culprit for the longer loadtimes might not be the instance!

I also made sure to double check if any resource limitations are in place for the nuxt3-auth docker containter, which is not the case and based on `docker stats` the container has the full resource capabilities available.

**Comment by BracketJohn** [comment] 2022-12-03 16:02
One important metric to look at for SSR is actually also RAM (: 

The upgrade did the trick, the page is now much faster and we even got positive user feedback for it.

Closing this issue (:

**Closed as completed** 2022-12-03 16:03 UTC
Labels: bug
